[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ipc"
version = "0.1.0"
description = "Asynchronous implementation of the Majordomo broker"
authors = [
    {name = "Void-ux", email = "77840397+Void-ux@users.noreply.github.com"},
]
dependencies = [
    "pyzmq>=26.4.0",
    "msgpack>=1.1.0",
]
requires-python = "<4.0,>=3.10"
readme = "README.md"
license = "MIT"

[project.optional-dependencies]
worker = [
    "discord-py",
]

[tool.pdm]
distribution = false

[tool.pdm.build]
includes = ["src/"]

[tool.setuptools.packages.find]
where = ["src/"]

[tool.setuptools.package-data]
ipc = ["py.typed"]

[dependency-groups]
dev = ["ruff>=0.12.0", "pyright>=1.1.403"]

[tool.ruff]
target-version = "py310"
line-length = 125

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "ASYNC"]

[tool.ruff.format]
quote-style = "single"

[tool.pyright]
include = ["src", "tests/typing_routes.py"]
pythonVersion = "3.10"
typeCheckingMode = "strict"
